services:
  web:
    build: .
    ports:
      - "80:5000"
    environment:
      REDIS_HOST: redis
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydatabase
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      
    networks:
      - capstone-network
  
  redis:
    image: redis:latest
    restart: always
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 2s
        timeout: 20s
        retries: 10
    networks:
      - capstone-network

  
  db:
    image: mysql
    restart: always
    volumes:
      - db-data-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10
    networks:
      - capstone-network
  
  test:
    build: .
    command: python test_app.py
    
networks:
  capstone-network:
    driver: bridge

volumes:
  db-data-mysql: