name: Capstone Project
services:
  web:
    image: aalahideb/flask-app:latest
    ports:
      - "80:5000"
    env_file: ".env"
    networks:
      - capstone-network
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - capstone-network

  
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db-data-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    networks:
      - capstone-network

networks:
  capstone-network:
    driver: bridge

volumes:
  db-data-mysql: