---
    name: deploy docker image
    on:
      push:
        branches:
          - cd
    jobs:
        deploy:
            runs-on: self-hosted
            strategy:
                matrix:
                    servers: ["10.0.2.227", "10.0.2.228"]
            steps:
                - name: Deploying docker image
                  env:
                    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                    SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
                  run: |
                        ssh-keyscan -H ${{ matrix.servers }} >> ~/.ssh/known_hosts
                        echo "$SSH_PRIVATE_KEY" > ~/.ssh/ssh_key
                        chmod 600 ~/.ssh/ssh_key
                        ssh -i ~/.ssh/ssh_key $SSH_USERNAME@${{ matrix.servers }} "ls && docker ps && docker images"
                        # ssh -i ~/.ssh/ssh_key $SSH_USERNAME@${{ matrix.servers }} "docker pull ${{ secrets.DOCKER_USERNAME }}/flask-app:latest && docker compose up web --build -d"

            